name: Auto Comment
on: pull_request_target

jobs:
  local-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            `./scripts/checkout.py ${{ github.event.user.login }} ${{ github.event.head.ref }}` - type in repo root to checkout this change locally"}
